-- MySQL Script generated by MySQL Workbench
-- lun 30 mar 2026 17:28:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ComidApp` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ComidApp` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ComidApp` ;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `dniUsuario` INT NOT NULL,
  `esAdmin` TINYINT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`dniUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `dniUsuario` INT NOT NULL,
  `dirEntrega` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`dniUsuario`),
  FOREIGN KEY (`dniUsuario`) references usuario(dniUsuario)
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `repartidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `repartidor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `repartidor` (
  `dniUsuario` INT NOT NULL,
  `disponible` TINYINT NOT NULL,
  PRIMARY KEY (`dniUsuario`, `disponible`),
  FOREIGN KEY (`dniUsuario`) references usuario(dniUsuario)
)
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `producto` (
  `idProd` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripción` VARCHAR(45) NULL,
  `disponible` TINYINT,
  `imagen` VARCHAR (45) NULL,
  `categoria` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`idProd`)
)
ENGINE = InnoDB;

SHOW WARNINGS;




-- -----------------------------------------------------
-- Table `local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `local` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `activo` TINYINT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `local_has_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `local_has_producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `local_has_producto` (
  `local_id` INT NOT NULL,
  `producto_idProd` INT NOT NULL,
  `stock` int not null,
  PRIMARY KEY (`local_id`, `producto_idProd`),
  FOREIGN KEY (`local_id`) REFERENCES local(id),
  FOREIGN KEY (`producto_idProd`) REFERENCES producto(idProd)
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaHora` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `total` FLOAT NOT NULL,
  `cliente_dniUsuario` INT NOT NULL,
  `repartidor_dniUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  foreign key (`cliente_dniUsuario`) references cliente(dniUsuario),
  foreign key (`repartidor_dniUsuario`) references repartidor(dniUsuario)
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prod_has_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prod_has_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `prod_has_pedido` (
  `producto_idProd` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` FLOAT NULL,
  `resumenProductos` VARCHAR(100) NULL,
  PRIMARY KEY (`producto_idProd`, `pedido_id`),
  foreign key (`producto_idProd`) references producto(idProd),
  foreign key (`pedido_id`) references pedido(id)
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pago` (
  `idPago` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  `monto` FLOAT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPago`),
  FOREIGN KEY (`pedido_id`) REFERENCES pedido(id)
)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
